services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: PASS
      POSTGRES_DB: NAME
    container_name: crud_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
